version: '3'

services: 
  app: 
    build: .
    container_name: nodejs-ms-conpact-myspace
    volumes:
      - .:/home/node/app
      - ./.docker/zsh/powerlevel10k/.p10k.zsh:/home/node/.p10k.zsh:delegated
      - ./.docker/zsh/history:/home/node/zsh:delegated
    ports:
      - 3000:3000
